### PR TITLE
renamed folders and add a little bit of readme

### LINKED ISSUE #25: designate a models folder
replaces result folder

### PR DESCRIPTION
**Pull request by Jopyth**
Fixes #25

### CODE REVIEW

**Comment by Jopyth** [comment]
Should we include the urls in the readme?

**Comment by Jopyth** [comment]
I also improved generation scripts a little bit and the readme for them.

**Comment by Bartzi** [comment]
which urls are you thinking of?

**Comment by Bartzi** [comment]
Nevermid, I think I found the URL you mentioned. I think we can include them =)

**Pull request merged**
